### ISSUE TITLE
error occuring

### ISSUE THREAD

**Issue by ayushibisen01** [FardeenMohammed/AI_Virtual_Painter_2.0#2]
E:\painter\Scripts\python.exe E:/painter/Lib/site-packages/HandTrackingModule/__init__.py
Traceback (most recent call last):
  File "E:\painter\Lib\site-packages\HandTrackingModule\__init__.py", line 116, in <module>
    main()
  File "E:\painter\Lib\site-packages\HandTrackingModule\__init__.py", line 96, in main
    detector = handDetector()
  File "E:\painter\Lib\site-packages\HandTrackingModule\__init__.py", line 16, in __init__
    self.hands = self.mpHands.Hands(self.mode, self.maxHands,
  File "E:\painter\lib\site-packages\mediapipe\python\solutions\hands.py", line 114, in __init__
    super().__init__(
  File "E:\painter\lib\site-packages\mediapipe\python\solution_base.py", line 290, in __init__
    self._input_side_packets = {
  File "E:\painter\lib\site-packages\mediapipe\python\solution_base.py", line 291, in <dictcomp>
    name: self._make_packet(self._side_input_type_info[name], data)
  File "E:\painter\lib\site-packages\mediapipe\python\solution_base.py", line 593, in _make_packet
    return getattr(packet_creator, 'create_' + packet_data_type.value)(data)
TypeError: create_int(): incompatible function arguments. The following argument types are supported:
    1. (arg0: int) -> mediapipe.python._framework_bindings.packet.Packet

Invoked with: 0.5

Process finished with exit code 1

**Comment by FardeenMohammed** [comment]
Something is wrong with versions you are using

**Comment by ayushibisen01** [comment]
Which version to use??

**Comment by FardeenMohammed** [comment]
can you share all the versions you have currently installed?
